# Generated by Django 3.2.4 on 2021-08-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialNewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='short_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
