# Generated by Django 3.2.4 on 2021-08-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialNewsApp', '0002_auto_20210809_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='short_name',
            field=models.CharField(max_length=10),
        ),
    ]
